config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<div class="row"><div class="col-sm-12 sectionHeader"><h1>So what's the dealio?</h1></div></div>

  <blockquote>
  <header>What is it?</header>
<p>twatter is a microposting site where you share with other users through short blurbs of text called twats</p>
  </blockquote> 

    <blockquote>

  <header>How is it different from twitter? </header>
  <p>Good question!
 twatter is more than a simple twitter clone with slight name changes.
 It's a community! Where people can reach out to other twattelers.</p>
  </blockquote> 

    <blockquote>
  <header>Does it have follower system? </header>
  <p>twatter is about equality of opinion,
 therefor there are no leaders or followers on twatter, only close-knit communities
 of close-minded people called twattles, but, yes, it does have follower functionality.</p>
  </blockquote> 

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>
  <div class="row"><div class="col-sm-12 sectionHeader"><h1>Contact information</h1></div></div>

<p>Want to speak to us? Have something to share? We want to hear about. You don't even have to call us!</p>

<p>We have talented and dedicated guest experience agents calling customers around the clock to get their input.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<div class="row"><div class="col-sm-12 sectionHeader"><h1>Having problems?</h1></div></div>

<p>If the problems you are facing are of an urgent nature please call 911 instead</p>

<p>Otherwise please call one of our twelve call centres - where you're 1st in our hearts, but 234th in queue</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
    <div class="center jumbotron">
        <h1>Welcome to twatter</h1>
        <%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
  <div class="row"><div class="col-sm-12 sectionHeader"><h1>Reviews</h1></div></div>

  <blockquote>
  <p>"twatter is the peak of software engineering"</p>
  <footer>Lucas</footer>
  </blockquote> 
  
  <blockquote>
  <p>"twatter is a must for modern influencers looking to make a real impact on a fake platform"</p>
  <footer>test_user_12</footer>
  </blockquote>

  <blockquote>
    <p>"twatter is all the things twitter used to be for me like friendship, the envy of
     other people's lives from my graduating class who are doing better than me, and budget byte recipes,
      but in a way more streamlined and comprehensive package"</p>
  <footer>paid actor</footer>
  </blockquote>
  



<% end %>